
struct _t_segmento;
typedef struct _t_segmento t_segmento;

int AtiendeCliente(void * arg);
int DemasiadosClientes(int socket, struct sockaddr_in addr);
void Error(const char* mensaje, ...);
void Traza(const char* mensaje, ...);
void HiloOrquestadorDeConexiones();
void HiloConsola();
int RecibirDatos(int socket, void *buffer);
int ObtenerTamanioMemoriaConfig();
int ObtenerPuertoConfig();
void InstanciarTablaSegmentos();
void reservarMemoriaPrincipal();
void ErrorFatal(char mensaje[]);
void AgregarSegmentoALista(int idPrograma, int idSegmento, int inicio, int tamanio, char* ubicacionMP);
char* CalcularUbicacionMP(int tamanioSegmento);
int CrearSegmento(int idPrograma, int tamanio);
int chartToInt(char x);
void CerrarSocket(int socket);
char* NombreDeAlgoritmo(char idAlgorit);
int ValidarCodigoAlgoritmo(char idAlgorit);
int TraducirSiNo(char caracter);
int CalcularIdSegmento(int idPrograma);
int numeroAleatorio(int desde, int hasta);
int CalcularInicioSegmento(int idPrograma);
char* CalcularUbicacionMP_FirstFit(int tamanioRequeridoSegmento);
char* CalcularUbicacionMP_WorstFit(int tamanioRequeridoSegmento);
void ImprimirListadoSegmentosDeProgramaTSeg(int imprimirArchivo, t_segmento *Programa);
void ImprimirListadoSegmentosDePrograma(int imprimirArchivo, int idPrograma);
int ObtenerCantidadSegmentos();
void ImprimirListadoSegmentos(int imprimirArchivo);
int DestruirSegmentos(int idPrograma);
t_segmento* ObtenerInfoSegmento(int idPrograma, int idSegmento);
void ImprimirEncabezadoDeListadoSegmentos(int imprimirArchivo);
void ImprimirResuladoDeCrearSegmento(int idPrograma, int idSegmento, int tamanio, int imprimirArchivo);
void ImprimirBaseMemoria(int imprimirArchivo);
void ImprimirResumenUsoMemoria(int imprimirArchivo);
int obtenerTotalMemoriaEnUso();
void ImprimirResuladoDeDestruirSegmento(int idPrograma, int ok, int imprimirArchivo);
void CompactarMemoria();
void ImprimirResuladoDeEscribirMemoria(int ok, int idPrograma, int base, int desplazamiento, int cantidadBytes, char* buffer, int imprimirArchivo);
char * ObtenerUbicacionMPEnBaseAUbicacionVirtual(int idPrograma, int base);
int VerificarAccesoMemoria(int idPrograma, int base, int desplazamiento, int cantidadBytes);
int EscribirMemoria(int idPrograma, int base, int desplazamiento, int cantidadBytes, char* buffer);
int cantidadCaracteres(char* buffer);
void ImprimirResuladoDeLeerMemoria(int ok, int idPrograma, int base, int desplazamiento, int cantidadBytes, char* buffer, int imprimirArchivo);
int LeerMemoria(int idPrograma, int base, int desplazamiento, int cantidadBytes, char* buffer);
//Comandos mensajes
int ObtenerComandoMSJ(char buffer[]);
void ComandoGetBytes(char *buffer, int idProg);
void ComandoSetBytes(char *buffer, int idProg);
void ComandoHandShake(char *buffer, int *idProg, int *tipoCliente );
void ComandoCambioProceso(char *buffer, int *idProg);
void ComandoCrearSegmento(char *buffer, int idProg);
void ComandoDestruirSegmento(char *buffer, int idProg);
//Comandos consola
int ObtenerComandoConsola(char buffer[]);
void ConsolaComandoHelp();
void ConsolaComandoLeerMemoria();
void ConsolaComandoEscribirMemoria();
void ConsolaComandoCrearSegmento();
void ConsolaComandoDestruirSegmento();
void ConsolaComandoDefinirAlgoritmo();
void ConsolaComandoDefinirRetardo();
void ConsolaComandoCompactarMemoria();
void ConsolaComandoDumpEstructuras();
void ConsolaComandoDumpMemoriaPrincipal();
void ConsolaComandoDumpContenidoMemoriaPrincipal();

